"""create users table

Revision ID: 8a153de14882
Revises: 
Create Date: 2024-08-16 14:14:06.726515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a153de14882'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_choices_choice_text', table_name='choices')
    op.drop_index('ix_choices_id', table_name='choices')
    op.drop_table('choices')
    op.drop_index('ix_questions_id', table_name='questions')
    op.drop_index('ix_questions_question_text', table_name='questions')
    op.drop_table('questions')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'email')
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_questions_question_text', 'questions', ['question_text'], unique=False)
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('choice_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='choices_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='choices_pkey')
    )
    op.create_index('ix_choices_id', 'choices', ['id'], unique=False)
    op.create_index('ix_choices_choice_text', 'choices', ['choice_text'], unique=False)
    # ### end Alembic commands ###
